# Generated by Django 5.0.5 on 2024-05-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('video_url', models.URLField(max_length=1000)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
